<?php

/**
 * @file
 * Contains the Dashboards Auto Refresh module.
 *
 * This module allows custom blocks to auto-reload within dashboards.
 * It extends the Dashboards with Layouts module in Drupal.
 */

/**
 * Implements hook_preprocess_block().
 *
 * Prepares block variables for rendering.
 *
 * @param array &$variables
 *   An associative array containing the block variables.
 */
function dashboards_auto_refresh_preprocess_block(&$variables) {
  if (
    isset($variables['attributes']) &&
    isset($variables['attributes']['class']) &&
    in_array('dashboard-gin-panel', $variables['attributes']['class'])
  ) {
    if (isset($variables['plugin_id']) &&
        $variables['plugin_id'] != 'entity_block:node' &&
        $variables['plugin_id'] != 'clock_block') {
      $variables['content']['#attributes']['id'] = $variables['plugin_id'];
    }
  }
}

/**
 * Implements hook_page_attachments().
 *
 * Attaches the polling library to the dashboard page.
 *
 * @param array &$variables
 *   An associative array containing the page variables.
 */
function dashboards_auto_refresh_page_attachments(&$variables) {
  $current_uri = explode('/', \Drupal::request()->getRequestUri());
  if (count($current_uri) > 1 && $current_uri[1] == 'dashboard') {
    $variables['#attached']['library'][] = 'dashboards_auto_refresh/polling';
  }
}
